// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package validator

import (
	"github.com/odarbelaeze/openapier/pkg/schema/options"
	mock "github.com/stretchr/testify/mock"
)

// NewMockValidatorTag creates a new instance of MockValidatorTag. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidatorTag(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidatorTag {
	mock := &MockValidatorTag{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidatorTag is an autogenerated mock type for the ValidatorTag type
type MockValidatorTag struct {
	mock.Mock
}

type MockValidatorTag_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidatorTag) EXPECT() *MockValidatorTag_Expecter {
	return &MockValidatorTag_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockValidatorTag
func (_mock *MockValidatorTag) Parse(s string, s1 string) ([]options.SchemaOption, error) {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 []options.SchemaOption
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]options.SchemaOption, error)); ok {
		return returnFunc(s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []options.SchemaOption); ok {
		r0 = returnFunc(s, s1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]options.SchemaOption)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockValidatorTag_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockValidatorTag_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *MockValidatorTag_Expecter) Parse(s interface{}, s1 interface{}) *MockValidatorTag_Parse_Call {
	return &MockValidatorTag_Parse_Call{Call: _e.mock.On("Parse", s, s1)}
}

func (_c *MockValidatorTag_Parse_Call) Run(run func(s string, s1 string)) *MockValidatorTag_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockValidatorTag_Parse_Call) Return(schemaOptions []options.SchemaOption, err error) *MockValidatorTag_Parse_Call {
	_c.Call.Return(schemaOptions, err)
	return _c
}

func (_c *MockValidatorTag_Parse_Call) RunAndReturn(run func(s string, s1 string) ([]options.SchemaOption, error)) *MockValidatorTag_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// Tag provides a mock function for the type MockValidatorTag
func (_mock *MockValidatorTag) Tag() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tag")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockValidatorTag_Tag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tag'
type MockValidatorTag_Tag_Call struct {
	*mock.Call
}

// Tag is a helper method to define mock.On call
func (_e *MockValidatorTag_Expecter) Tag() *MockValidatorTag_Tag_Call {
	return &MockValidatorTag_Tag_Call{Call: _e.mock.On("Tag")}
}

func (_c *MockValidatorTag_Tag_Call) Run(run func()) *MockValidatorTag_Tag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValidatorTag_Tag_Call) Return(s string) *MockValidatorTag_Tag_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockValidatorTag_Tag_Call) RunAndReturn(run func() string) *MockValidatorTag_Tag_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type MockValidatorTag
func (_mock *MockValidatorTag) Usage() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockValidatorTag_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type MockValidatorTag_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
func (_e *MockValidatorTag_Expecter) Usage() *MockValidatorTag_Usage_Call {
	return &MockValidatorTag_Usage_Call{Call: _e.mock.On("Usage")}
}

func (_c *MockValidatorTag_Usage_Call) Run(run func()) *MockValidatorTag_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValidatorTag_Usage_Call) Return(s string) *MockValidatorTag_Usage_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockValidatorTag_Usage_Call) RunAndReturn(run func() string) *MockValidatorTag_Usage_Call {
	_c.Call.Return(run)
	return _c
}
