// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package parsermocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/sv-tools/openapi"
)

// NewMockParser creates a new instance of MockParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParser {
	mock := &MockParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParser is an autogenerated mock type for the Parser type
type MockParser struct {
	mock.Mock
}

type MockParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParser) EXPECT() *MockParser_Expecter {
	return &MockParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockParser
func (_mock *MockParser) Parse() (*openapi.Extendable[openapi.OpenAPI], error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *openapi.Extendable[openapi.OpenAPI]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*openapi.Extendable[openapi.OpenAPI], error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *openapi.Extendable[openapi.OpenAPI]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openapi.Extendable[openapi.OpenAPI])
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
func (_e *MockParser_Expecter) Parse() *MockParser_Parse_Call {
	return &MockParser_Parse_Call{Call: _e.mock.On("Parse")}
}

func (_c *MockParser_Parse_Call) Run(run func()) *MockParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParser_Parse_Call) Return(extendable *openapi.Extendable[openapi.OpenAPI], err error) *MockParser_Parse_Call {
	_c.Call.Return(extendable, err)
	return _c
}

func (_c *MockParser_Parse_Call) RunAndReturn(run func() (*openapi.Extendable[openapi.OpenAPI], error)) *MockParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}
