// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package validatormocks

import (
	"github.com/odarbelaeze/openapier/schema/options"
	"github.com/odarbelaeze/openapier/schema/validator"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

type MockRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistry) EXPECT() *MockRegistry_Expecter {
	return &MockRegistry_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Parse(s string, s1 string) ([]options.SchemaOption, error) {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 []options.SchemaOption
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]options.SchemaOption, error)); ok {
		return returnFunc(s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []options.SchemaOption); ok {
		r0 = returnFunc(s, s1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]options.SchemaOption)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistry_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockRegistry_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *MockRegistry_Expecter) Parse(s interface{}, s1 interface{}) *MockRegistry_Parse_Call {
	return &MockRegistry_Parse_Call{Call: _e.mock.On("Parse", s, s1)}
}

func (_c *MockRegistry_Parse_Call) Run(run func(s string, s1 string)) *MockRegistry_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegistry_Parse_Call) Return(schemaOptions []options.SchemaOption, err error) *MockRegistry_Parse_Call {
	_c.Call.Return(schemaOptions, err)
	return _c
}

func (_c *MockRegistry_Parse_Call) RunAndReturn(run func(s string, s1 string) ([]options.SchemaOption, error)) *MockRegistry_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Register(tag validator.Tag) {
	_mock.Called(tag)
	return
}

// MockRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - tag validator.Tag
func (_e *MockRegistry_Expecter) Register(tag interface{}) *MockRegistry_Register_Call {
	return &MockRegistry_Register_Call{Call: _e.mock.On("Register", tag)}
}

func (_c *MockRegistry_Register_Call) Run(run func(tag validator.Tag)) *MockRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 validator.Tag
		if args[0] != nil {
			arg0 = args[0].(validator.Tag)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_Register_Call) Return() *MockRegistry_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRegistry_Register_Call) RunAndReturn(run func(tag validator.Tag)) *MockRegistry_Register_Call {
	_c.Run(run)
	return _c
}

// Validators provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Validators() []validator.Tag {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validators")
	}

	var r0 []validator.Tag
	if returnFunc, ok := ret.Get(0).(func() []validator.Tag); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]validator.Tag)
		}
	}
	return r0
}

// MockRegistry_Validators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validators'
type MockRegistry_Validators_Call struct {
	*mock.Call
}

// Validators is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) Validators() *MockRegistry_Validators_Call {
	return &MockRegistry_Validators_Call{Call: _e.mock.On("Validators")}
}

func (_c *MockRegistry_Validators_Call) Run(run func()) *MockRegistry_Validators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_Validators_Call) Return(tags []validator.Tag) *MockRegistry_Validators_Call {
	_c.Call.Return(tags)
	return _c
}

func (_c *MockRegistry_Validators_Call) RunAndReturn(run func() []validator.Tag) *MockRegistry_Validators_Call {
	_c.Call.Return(run)
	return _c
}
