// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package validatormocks

import (
	"github.com/odarbelaeze/openapier/schema/options"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTag creates a new instance of MockTag. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTag(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTag {
	mock := &MockTag{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTag is an autogenerated mock type for the Tag type
type MockTag struct {
	mock.Mock
}

type MockTag_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTag) EXPECT() *MockTag_Expecter {
	return &MockTag_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockTag
func (_mock *MockTag) Parse(value string, as string) ([]options.SchemaOption, error) {
	ret := _mock.Called(value, as)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 []options.SchemaOption
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]options.SchemaOption, error)); ok {
		return returnFunc(value, as)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []options.SchemaOption); ok {
		r0 = returnFunc(value, as)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]options.SchemaOption)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(value, as)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTag_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockTag_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - value string
//   - as string
func (_e *MockTag_Expecter) Parse(value interface{}, as interface{}) *MockTag_Parse_Call {
	return &MockTag_Parse_Call{Call: _e.mock.On("Parse", value, as)}
}

func (_c *MockTag_Parse_Call) Run(run func(value string, as string)) *MockTag_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTag_Parse_Call) Return(schemaOptions []options.SchemaOption, err error) *MockTag_Parse_Call {
	_c.Call.Return(schemaOptions, err)
	return _c
}

func (_c *MockTag_Parse_Call) RunAndReturn(run func(value string, as string) ([]options.SchemaOption, error)) *MockTag_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// Tag provides a mock function for the type MockTag
func (_mock *MockTag) Tag() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tag")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTag_Tag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tag'
type MockTag_Tag_Call struct {
	*mock.Call
}

// Tag is a helper method to define mock.On call
func (_e *MockTag_Expecter) Tag() *MockTag_Tag_Call {
	return &MockTag_Tag_Call{Call: _e.mock.On("Tag")}
}

func (_c *MockTag_Tag_Call) Run(run func()) *MockTag_Tag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTag_Tag_Call) Return(s string) *MockTag_Tag_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTag_Tag_Call) RunAndReturn(run func() string) *MockTag_Tag_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type MockTag
func (_mock *MockTag) Usage() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTag_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type MockTag_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
func (_e *MockTag_Expecter) Usage() *MockTag_Usage_Call {
	return &MockTag_Usage_Call{Call: _e.mock.On("Usage")}
}

func (_c *MockTag_Usage_Call) Run(run func()) *MockTag_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTag_Usage_Call) Return(s string) *MockTag_Usage_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTag_Usage_Call) RunAndReturn(run func() string) *MockTag_Usage_Call {
	_c.Call.Return(run)
	return _c
}
