// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resolvermocks

import (
	"go/ast"

	"github.com/odarbelaeze/openapier/pkg/schema/options"
	"github.com/odarbelaeze/openapier/pkg/schema/resolver"
	mock "github.com/stretchr/testify/mock"
	"github.com/sv-tools/openapi"
)

// NewMockResolver creates a new instance of MockResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolver {
	mock := &MockResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResolver is an autogenerated mock type for the Resolver type
type MockResolver struct {
	mock.Mock
}

type MockResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolver) EXPECT() *MockResolver_Expecter {
	return &MockResolver_Expecter{mock: &_m.Mock}
}

// From provides a mock function for the type MockResolver
func (_mock *MockResolver) From(file *ast.File, from string) resolver.Resolver {
	ret := _mock.Called(file, from)

	if len(ret) == 0 {
		panic("no return value specified for From")
	}

	var r0 resolver.Resolver
	if returnFunc, ok := ret.Get(0).(func(*ast.File, string) resolver.Resolver); ok {
		r0 = returnFunc(file, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resolver.Resolver)
		}
	}
	return r0
}

// MockResolver_From_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'From'
type MockResolver_From_Call struct {
	*mock.Call
}

// From is a helper method to define mock.On call
//   - file *ast.File
//   - from string
func (_e *MockResolver_Expecter) From(file interface{}, from interface{}) *MockResolver_From_Call {
	return &MockResolver_From_Call{Call: _e.mock.On("From", file, from)}
}

func (_c *MockResolver_From_Call) Run(run func(file *ast.File, from string)) *MockResolver_From_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ast.File
		if args[0] != nil {
			arg0 = args[0].(*ast.File)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockResolver_From_Call) Return(resolver1 resolver.Resolver) *MockResolver_From_Call {
	_c.Call.Return(resolver1)
	return _c
}

func (_c *MockResolver_From_Call) RunAndReturn(run func(file *ast.File, from string) resolver.Resolver) *MockResolver_From_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function for the type MockResolver
func (_mock *MockResolver) Resolve(typeName string, opts ...options.SchemaOption) (*openapi.RefOrSpec[openapi.Schema], error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(typeName, opts)
	} else {
		tmpRet = _mock.Called(typeName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 *openapi.RefOrSpec[openapi.Schema]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...options.SchemaOption) (*openapi.RefOrSpec[openapi.Schema], error)); ok {
		return returnFunc(typeName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...options.SchemaOption) *openapi.RefOrSpec[openapi.Schema]); ok {
		r0 = returnFunc(typeName, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openapi.RefOrSpec[openapi.Schema])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...options.SchemaOption) error); ok {
		r1 = returnFunc(typeName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - typeName string
//   - opts ...options.SchemaOption
func (_e *MockResolver_Expecter) Resolve(typeName interface{}, opts ...interface{}) *MockResolver_Resolve_Call {
	return &MockResolver_Resolve_Call{Call: _e.mock.On("Resolve",
		append([]interface{}{typeName}, opts...)...)}
}

func (_c *MockResolver_Resolve_Call) Run(run func(typeName string, opts ...options.SchemaOption)) *MockResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []options.SchemaOption
		var variadicArgs []options.SchemaOption
		if len(args) > 1 {
			variadicArgs = args[1].([]options.SchemaOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockResolver_Resolve_Call) Return(refOrSpec *openapi.RefOrSpec[openapi.Schema], err error) *MockResolver_Resolve_Call {
	_c.Call.Return(refOrSpec, err)
	return _c
}

func (_c *MockResolver_Resolve_Call) RunAndReturn(run func(typeName string, opts ...options.SchemaOption) (*openapi.RefOrSpec[openapi.Schema], error)) *MockResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
