// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cache

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/sv-tools/openapi"
)

// NewMockDefinitionsCache creates a new instance of MockDefinitionsCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDefinitionsCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDefinitionsCache {
	mock := &MockDefinitionsCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDefinitionsCache is an autogenerated mock type for the DefinitionsCache type
type MockDefinitionsCache struct {
	mock.Mock
}

type MockDefinitionsCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDefinitionsCache) EXPECT() *MockDefinitionsCache_Expecter {
	return &MockDefinitionsCache_Expecter{mock: &_m.Mock}
}

// Definitions provides a mock function for the type MockDefinitionsCache
func (_mock *MockDefinitionsCache) Definitions() map[string]*openapi.RefOrSpec[openapi.Schema] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Definitions")
	}

	var r0 map[string]*openapi.RefOrSpec[openapi.Schema]
	if returnFunc, ok := ret.Get(0).(func() map[string]*openapi.RefOrSpec[openapi.Schema]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*openapi.RefOrSpec[openapi.Schema])
		}
	}
	return r0
}

// MockDefinitionsCache_Definitions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Definitions'
type MockDefinitionsCache_Definitions_Call struct {
	*mock.Call
}

// Definitions is a helper method to define mock.On call
func (_e *MockDefinitionsCache_Expecter) Definitions() *MockDefinitionsCache_Definitions_Call {
	return &MockDefinitionsCache_Definitions_Call{Call: _e.mock.On("Definitions")}
}

func (_c *MockDefinitionsCache_Definitions_Call) Run(run func()) *MockDefinitionsCache_Definitions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDefinitionsCache_Definitions_Call) Return(stringToRefOrSpec map[string]*openapi.RefOrSpec[openapi.Schema]) *MockDefinitionsCache_Definitions_Call {
	_c.Call.Return(stringToRefOrSpec)
	return _c
}

func (_c *MockDefinitionsCache_Definitions_Call) RunAndReturn(run func() map[string]*openapi.RefOrSpec[openapi.Schema]) *MockDefinitionsCache_Definitions_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockDefinitionsCache
func (_mock *MockDefinitionsCache) Get(s string) (*openapi.RefOrSpec[openapi.Schema], bool) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *openapi.RefOrSpec[openapi.Schema]
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (*openapi.RefOrSpec[openapi.Schema], bool)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *openapi.RefOrSpec[openapi.Schema]); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openapi.RefOrSpec[openapi.Schema])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockDefinitionsCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDefinitionsCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - s string
func (_e *MockDefinitionsCache_Expecter) Get(s interface{}) *MockDefinitionsCache_Get_Call {
	return &MockDefinitionsCache_Get_Call{Call: _e.mock.On("Get", s)}
}

func (_c *MockDefinitionsCache_Get_Call) Run(run func(s string)) *MockDefinitionsCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDefinitionsCache_Get_Call) Return(refOrSpec *openapi.RefOrSpec[openapi.Schema], b bool) *MockDefinitionsCache_Get_Call {
	_c.Call.Return(refOrSpec, b)
	return _c
}

func (_c *MockDefinitionsCache_Get_Call) RunAndReturn(run func(s string) (*openapi.RefOrSpec[openapi.Schema], bool)) *MockDefinitionsCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockDefinitionsCache
func (_mock *MockDefinitionsCache) Put(s string, refOrSpec *openapi.RefOrSpec[openapi.Schema]) {
	_mock.Called(s, refOrSpec)
	return
}

// MockDefinitionsCache_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockDefinitionsCache_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - s string
//   - refOrSpec *openapi.RefOrSpec[openapi.Schema]
func (_e *MockDefinitionsCache_Expecter) Put(s interface{}, refOrSpec interface{}) *MockDefinitionsCache_Put_Call {
	return &MockDefinitionsCache_Put_Call{Call: _e.mock.On("Put", s, refOrSpec)}
}

func (_c *MockDefinitionsCache_Put_Call) Run(run func(s string, refOrSpec *openapi.RefOrSpec[openapi.Schema])) *MockDefinitionsCache_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *openapi.RefOrSpec[openapi.Schema]
		if args[1] != nil {
			arg1 = args[1].(*openapi.RefOrSpec[openapi.Schema])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDefinitionsCache_Put_Call) Return() *MockDefinitionsCache_Put_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDefinitionsCache_Put_Call) RunAndReturn(run func(s string, refOrSpec *openapi.RefOrSpec[openapi.Schema])) *MockDefinitionsCache_Put_Call {
	_c.Run(run)
	return _c
}
