// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package specmocks

import (
	"github.com/odarbelaeze/openapier/comments/spec"
	mock "github.com/stretchr/testify/mock"
	"github.com/sv-tools/openapi"
)

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

type MockRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistry) EXPECT() *MockRegistry_Expecter {
	return &MockRegistry_Expecter{mock: &_m.Mock}
}

// Comments provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Comments() []spec.Comment {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Comments")
	}

	var r0 []spec.Comment
	if returnFunc, ok := ret.Get(0).(func() []spec.Comment); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]spec.Comment)
		}
	}
	return r0
}

// MockRegistry_Comments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Comments'
type MockRegistry_Comments_Call struct {
	*mock.Call
}

// Comments is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) Comments() *MockRegistry_Comments_Call {
	return &MockRegistry_Comments_Call{Call: _e.mock.On("Comments")}
}

func (_c *MockRegistry_Comments_Call) Run(run func()) *MockRegistry_Comments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_Comments_Call) Return(comments []spec.Comment) *MockRegistry_Comments_Call {
	_c.Call.Return(comments)
	return _c
}

func (_c *MockRegistry_Comments_Call) RunAndReturn(run func() []spec.Comment) *MockRegistry_Comments_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Parse(line string, spec1 *openapi.Extendable[openapi.OpenAPI]) error {
	ret := _mock.Called(line, spec1)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *openapi.Extendable[openapi.OpenAPI]) error); ok {
		r0 = returnFunc(line, spec1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegistry_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockRegistry_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - line string
//   - spec1 *openapi.Extendable[openapi.OpenAPI]
func (_e *MockRegistry_Expecter) Parse(line interface{}, spec1 interface{}) *MockRegistry_Parse_Call {
	return &MockRegistry_Parse_Call{Call: _e.mock.On("Parse", line, spec1)}
}

func (_c *MockRegistry_Parse_Call) Run(run func(line string, spec1 *openapi.Extendable[openapi.OpenAPI])) *MockRegistry_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *openapi.Extendable[openapi.OpenAPI]
		if args[1] != nil {
			arg1 = args[1].(*openapi.Extendable[openapi.OpenAPI])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegistry_Parse_Call) Return(err error) *MockRegistry_Parse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistry_Parse_Call) RunAndReturn(run func(line string, spec1 *openapi.Extendable[openapi.OpenAPI]) error) *MockRegistry_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Register(c spec.Comment) {
	_mock.Called(c)
	return
}

// MockRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - c spec.Comment
func (_e *MockRegistry_Expecter) Register(c interface{}) *MockRegistry_Register_Call {
	return &MockRegistry_Register_Call{Call: _e.mock.On("Register", c)}
}

func (_c *MockRegistry_Register_Call) Run(run func(c spec.Comment)) *MockRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 spec.Comment
		if args[0] != nil {
			arg0 = args[0].(spec.Comment)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_Register_Call) Return() *MockRegistry_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRegistry_Register_Call) RunAndReturn(run func(c spec.Comment)) *MockRegistry_Register_Call {
	_c.Run(run)
	return _c
}
