// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package spec

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/sv-tools/openapi"
)

// NewMockComment creates a new instance of MockComment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComment(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComment {
	mock := &MockComment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockComment is an autogenerated mock type for the Comment type
type MockComment struct {
	mock.Mock
}

type MockComment_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComment) EXPECT() *MockComment_Expecter {
	return &MockComment_Expecter{mock: &_m.Mock}
}

// ParseInto provides a mock function for the type MockComment
func (_mock *MockComment) ParseInto(c string, s *openapi.Extendable[openapi.OpenAPI]) error {
	ret := _mock.Called(c, s)

	if len(ret) == 0 {
		panic("no return value specified for ParseInto")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *openapi.Extendable[openapi.OpenAPI]) error); ok {
		r0 = returnFunc(c, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockComment_ParseInto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseInto'
type MockComment_ParseInto_Call struct {
	*mock.Call
}

// ParseInto is a helper method to define mock.On call
//   - c string
//   - s *openapi.Extendable[openapi.OpenAPI]
func (_e *MockComment_Expecter) ParseInto(c interface{}, s interface{}) *MockComment_ParseInto_Call {
	return &MockComment_ParseInto_Call{Call: _e.mock.On("ParseInto", c, s)}
}

func (_c *MockComment_ParseInto_Call) Run(run func(c string, s *openapi.Extendable[openapi.OpenAPI])) *MockComment_ParseInto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *openapi.Extendable[openapi.OpenAPI]
		if args[1] != nil {
			arg1 = args[1].(*openapi.Extendable[openapi.OpenAPI])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComment_ParseInto_Call) Return(err error) *MockComment_ParseInto_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockComment_ParseInto_Call) RunAndReturn(run func(c string, s *openapi.Extendable[openapi.OpenAPI]) error) *MockComment_ParseInto_Call {
	_c.Call.Return(run)
	return _c
}

// Tag provides a mock function for the type MockComment
func (_mock *MockComment) Tag() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tag")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockComment_Tag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tag'
type MockComment_Tag_Call struct {
	*mock.Call
}

// Tag is a helper method to define mock.On call
func (_e *MockComment_Expecter) Tag() *MockComment_Tag_Call {
	return &MockComment_Tag_Call{Call: _e.mock.On("Tag")}
}

func (_c *MockComment_Tag_Call) Run(run func()) *MockComment_Tag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComment_Tag_Call) Return(s string) *MockComment_Tag_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockComment_Tag_Call) RunAndReturn(run func() string) *MockComment_Tag_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type MockComment
func (_mock *MockComment) Usage() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockComment_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type MockComment_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
func (_e *MockComment_Expecter) Usage() *MockComment_Usage_Call {
	return &MockComment_Usage_Call{Call: _e.mock.On("Usage")}
}

func (_c *MockComment_Usage_Call) Run(run func()) *MockComment_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComment_Usage_Call) Return(s string) *MockComment_Usage_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockComment_Usage_Call) RunAndReturn(run func() string) *MockComment_Usage_Call {
	_c.Call.Return(run)
	return _c
}
