// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cachemocks

import (
	"go/ast"

	mock "github.com/stretchr/testify/mock"
)

// NewMockParserCache creates a new instance of MockParserCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParserCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParserCache {
	mock := &MockParserCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParserCache is an autogenerated mock type for the ParserCache type
type MockParserCache struct {
	mock.Mock
}

type MockParserCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParserCache) EXPECT() *MockParserCache_Expecter {
	return &MockParserCache_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockParserCache
func (_mock *MockParserCache) Parse(filename string) (*ast.File, error) {
	ret := _mock.Called(filename)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *ast.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*ast.File, error)); ok {
		return returnFunc(filename)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *ast.File); ok {
		r0 = returnFunc(filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ast.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParserCache_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockParserCache_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - filename string
func (_e *MockParserCache_Expecter) Parse(filename interface{}) *MockParserCache_Parse_Call {
	return &MockParserCache_Parse_Call{Call: _e.mock.On("Parse", filename)}
}

func (_c *MockParserCache_Parse_Call) Run(run func(filename string)) *MockParserCache_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParserCache_Parse_Call) Return(file *ast.File, err error) *MockParserCache_Parse_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockParserCache_Parse_Call) RunAndReturn(run func(filename string) (*ast.File, error)) *MockParserCache_Parse_Call {
	_c.Call.Return(run)
	return _c
}
