// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cachemocks

import (
	"context"

	"github.com/odarbelaeze/openapier/pkg/cache"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTypeDefCache creates a new instance of MockTypeDefCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTypeDefCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTypeDefCache {
	mock := &MockTypeDefCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTypeDefCache is an autogenerated mock type for the TypeDefCache type
type MockTypeDefCache struct {
	mock.Mock
}

type MockTypeDefCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTypeDefCache) EXPECT() *MockTypeDefCache_Expecter {
	return &MockTypeDefCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockTypeDefCache
func (_mock *MockTypeDefCache) Get(pkgPath string, typeName string) (*cache.TypeDef, bool) {
	ret := _mock.Called(pkgPath, typeName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *cache.TypeDef
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) (*cache.TypeDef, bool)); ok {
		return returnFunc(pkgPath, typeName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *cache.TypeDef); ok {
		r0 = returnFunc(pkgPath, typeName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cache.TypeDef)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) bool); ok {
		r1 = returnFunc(pkgPath, typeName)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockTypeDefCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTypeDefCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - pkgPath string
//   - typeName string
func (_e *MockTypeDefCache_Expecter) Get(pkgPath interface{}, typeName interface{}) *MockTypeDefCache_Get_Call {
	return &MockTypeDefCache_Get_Call{Call: _e.mock.On("Get", pkgPath, typeName)}
}

func (_c *MockTypeDefCache_Get_Call) Run(run func(pkgPath string, typeName string)) *MockTypeDefCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTypeDefCache_Get_Call) Return(typeDef *cache.TypeDef, b bool) *MockTypeDefCache_Get_Call {
	_c.Call.Return(typeDef, b)
	return _c
}

func (_c *MockTypeDefCache_Get_Call) RunAndReturn(run func(pkgPath string, typeName string) (*cache.TypeDef, bool)) *MockTypeDefCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockTypeDefCache
func (_mock *MockTypeDefCache) Load(ctx context.Context, pkgPath string) error {
	ret := _mock.Called(ctx, pkgPath)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, pkgPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTypeDefCache_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockTypeDefCache_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - pkgPath string
func (_e *MockTypeDefCache_Expecter) Load(ctx interface{}, pkgPath interface{}) *MockTypeDefCache_Load_Call {
	return &MockTypeDefCache_Load_Call{Call: _e.mock.On("Load", ctx, pkgPath)}
}

func (_c *MockTypeDefCache_Load_Call) Run(run func(ctx context.Context, pkgPath string)) *MockTypeDefCache_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTypeDefCache_Load_Call) Return(err error) *MockTypeDefCache_Load_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTypeDefCache_Load_Call) RunAndReturn(run func(ctx context.Context, pkgPath string) error) *MockTypeDefCache_Load_Call {
	_c.Call.Return(run)
	return _c
}
