// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/odarbelaeze/openapier/pkg/schema/resolver (interfaces: Resolver)
//
// Generated by this command:
//
//	mockgen -destination=resolver_mock.go -package=resolver . Resolver
//

// Package resolver is a generated GoMock package.
package resolver

import (
	ast "go/ast"
	reflect "reflect"

	options "github.com/odarbelaeze/openapier/pkg/schema/options"
	openapi "github.com/sv-tools/openapi"
	gomock "go.uber.org/mock/gomock"
)

// MockResolver is a mock of Resolver interface.
type MockResolver struct {
	ctrl     *gomock.Controller
	recorder *MockResolverMockRecorder
	isgomock struct{}
}

// MockResolverMockRecorder is the mock recorder for MockResolver.
type MockResolverMockRecorder struct {
	mock *MockResolver
}

// NewMockResolver creates a new mock instance.
func NewMockResolver(ctrl *gomock.Controller) *MockResolver {
	mock := &MockResolver{ctrl: ctrl}
	mock.recorder = &MockResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResolver) EXPECT() *MockResolverMockRecorder {
	return m.recorder
}

// From mocks base method.
func (m *MockResolver) From(file *ast.File, from string) Resolver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "From", file, from)
	ret0, _ := ret[0].(Resolver)
	return ret0
}

// From indicates an expected call of From.
func (mr *MockResolverMockRecorder) From(file, from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "From", reflect.TypeOf((*MockResolver)(nil).From), file, from)
}

// Resolve mocks base method.
func (m *MockResolver) Resolve(typeName string, opts ...options.SchemaOption) (*openapi.RefOrSpec[openapi.Schema], error) {
	m.ctrl.T.Helper()
	varargs := []any{typeName}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Resolve", varargs...)
	ret0, _ := ret[0].(*openapi.RefOrSpec[openapi.Schema])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockResolverMockRecorder) Resolve(typeName any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{typeName}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockResolver)(nil).Resolve), varargs...)
}
