// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resolver

import (
	"go/ast"

	"github.com/odarbelaeze/openapier/pkg/schema/options"
	mock "github.com/stretchr/testify/mock"
	"github.com/sv-tools/openapi"
)

// NewMockSchemaBuilder creates a new instance of MockSchemaBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSchemaBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSchemaBuilder {
	mock := &MockSchemaBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSchemaBuilder is an autogenerated mock type for the SchemaBuilder type
type MockSchemaBuilder struct {
	mock.Mock
}

type MockSchemaBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSchemaBuilder) EXPECT() *MockSchemaBuilder_Expecter {
	return &MockSchemaBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockSchemaBuilder
func (_mock *MockSchemaBuilder) Build(expr ast.Expr, opts ...options.SchemaOption) (*openapi.RefOrSpec[openapi.Schema], error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(expr, opts)
	} else {
		tmpRet = _mock.Called(expr)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 *openapi.RefOrSpec[openapi.Schema]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ast.Expr, ...options.SchemaOption) (*openapi.RefOrSpec[openapi.Schema], error)); ok {
		return returnFunc(expr, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(ast.Expr, ...options.SchemaOption) *openapi.RefOrSpec[openapi.Schema]); ok {
		r0 = returnFunc(expr, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openapi.RefOrSpec[openapi.Schema])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ast.Expr, ...options.SchemaOption) error); ok {
		r1 = returnFunc(expr, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSchemaBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockSchemaBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - expr ast.Expr
//   - opts ...options.SchemaOption
func (_e *MockSchemaBuilder_Expecter) Build(expr interface{}, opts ...interface{}) *MockSchemaBuilder_Build_Call {
	return &MockSchemaBuilder_Build_Call{Call: _e.mock.On("Build",
		append([]interface{}{expr}, opts...)...)}
}

func (_c *MockSchemaBuilder_Build_Call) Run(run func(expr ast.Expr, opts ...options.SchemaOption)) *MockSchemaBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ast.Expr
		if args[0] != nil {
			arg0 = args[0].(ast.Expr)
		}
		var arg1 []options.SchemaOption
		var variadicArgs []options.SchemaOption
		if len(args) > 1 {
			variadicArgs = args[1].([]options.SchemaOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockSchemaBuilder_Build_Call) Return(refOrSpec *openapi.RefOrSpec[openapi.Schema], err error) *MockSchemaBuilder_Build_Call {
	_c.Call.Return(refOrSpec, err)
	return _c
}

func (_c *MockSchemaBuilder_Build_Call) RunAndReturn(run func(expr ast.Expr, opts ...options.SchemaOption) (*openapi.RefOrSpec[openapi.Schema], error)) *MockSchemaBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}
