// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resolver

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTypeDefCache creates a new instance of MockTypeDefCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTypeDefCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTypeDefCache {
	mock := &MockTypeDefCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTypeDefCache is an autogenerated mock type for the TypeDefCache type
type MockTypeDefCache struct {
	mock.Mock
}

type MockTypeDefCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTypeDefCache) EXPECT() *MockTypeDefCache_Expecter {
	return &MockTypeDefCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockTypeDefCache
func (_mock *MockTypeDefCache) Get(pkgName string, typeName string) (*TypeDef, bool) {
	ret := _mock.Called(pkgName, typeName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *TypeDef
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) (*TypeDef, bool)); ok {
		return returnFunc(pkgName, typeName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *TypeDef); ok {
		r0 = returnFunc(pkgName, typeName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TypeDef)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) bool); ok {
		r1 = returnFunc(pkgName, typeName)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockTypeDefCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTypeDefCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - pkgName string
//   - typeName string
func (_e *MockTypeDefCache_Expecter) Get(pkgName interface{}, typeName interface{}) *MockTypeDefCache_Get_Call {
	return &MockTypeDefCache_Get_Call{Call: _e.mock.On("Get", pkgName, typeName)}
}

func (_c *MockTypeDefCache_Get_Call) Run(run func(pkgName string, typeName string)) *MockTypeDefCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTypeDefCache_Get_Call) Return(typeDef *TypeDef, b bool) *MockTypeDefCache_Get_Call {
	_c.Call.Return(typeDef, b)
	return _c
}

func (_c *MockTypeDefCache_Get_Call) RunAndReturn(run func(pkgName string, typeName string) (*TypeDef, bool)) *MockTypeDefCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockTypeDefCache
func (_mock *MockTypeDefCache) Load(ctx context.Context, pkgName string) error {
	ret := _mock.Called(ctx, pkgName)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, pkgName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTypeDefCache_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockTypeDefCache_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - pkgName string
func (_e *MockTypeDefCache_Expecter) Load(ctx interface{}, pkgName interface{}) *MockTypeDefCache_Load_Call {
	return &MockTypeDefCache_Load_Call{Call: _e.mock.On("Load", ctx, pkgName)}
}

func (_c *MockTypeDefCache_Load_Call) Run(run func(ctx context.Context, pkgName string)) *MockTypeDefCache_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTypeDefCache_Load_Call) Return(err error) *MockTypeDefCache_Load_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTypeDefCache_Load_Call) RunAndReturn(run func(ctx context.Context, pkgName string) error) *MockTypeDefCache_Load_Call {
	_c.Call.Return(run)
	return _c
}
